
---

- name: make systemd drop-in directory
  file: path=/etc/systemd/system/docker.service.d state=directory owner=root group=root

- name: copy service conf for docker-engine service compatibility with docker
  copy: src=service.conf dest=/etc/systemd/system/docker.service.d/ owner=root group=root

- name: systemctl daemon reload
  shell: systemctl daemon-reload
